#!/usr/bin/env python3
"""Static module-coupling metrics from compile_commands.json (v1: include graph).

No LSP, no libclang, no compiler needed: reads compile_commands.json
(generated by `cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON`, configure only),
extracts include search paths, parses `#include` lines textually, and builds
a directory-module dependency graph. Reports:

  - module dependency cycles (strongly connected components)
  - unstable-but-widely-depended-on modules (high I = Ce/(Ca+Ce), high Ca)
  - per-module fan-in (Ca), fan-out (Ce), instability (I)

Stdlib only, Python 3.6+. Read-only.

Usage:
  cpp-coupling.py [options] <compile_commands.json | build-dir>

Options:
  --root DIR        project root; only files under it join the graph
                    (default: common path prefix of all translation units)
  --module-depth N  directory depth below root that defines a module
                    (default 2; e.g. root=llvm-project, depth 3 gives
                    llvm/lib/Support, depth 4 gives llvm/lib/Target/VE)
  --min-ca N        fan-in threshold for the instability warning (default 3)
  --top N           show at most N rows per section (default 20)
  --csv             CSV output: module,ca,ce,instability,in_cycle
  --fail-on-cycle   exit 1 if any module cycle exists (CI gate)

Exit codes: 0 = ok, 1 = --fail-on-cycle and a cycle exists, 2 = usage error.
"""

import json
import os
import re
import shlex
import sys

INCLUDE_RE = re.compile(r'^\s*#\s*include\s*(["<])([^">]+)[">]', re.M)


def die(msg):
    sys.stderr.write("error: %s\n" % msg)
    sys.exit(2)


def parse_args(argv):
    opts = {"root": None, "depth": 2, "min_ca": 3, "top": 20,
            "csv": False, "fail_on_cycle": False, "db": None}
    i = 1
    while i < len(argv):
        a = argv[i]

        def val():
            nonlocal i
            i += 1
            if i >= len(argv):
                die("%s needs a value" % a)
            return argv[i]

        if a == "--root":
            opts["root"] = os.path.realpath(val())
        elif a == "--module-depth":
            opts["depth"] = int(val())
        elif a == "--min-ca":
            opts["min_ca"] = int(val())
        elif a == "--top":
            opts["top"] = int(val())
        elif a == "--csv":
            opts["csv"] = True
        elif a == "--fail-on-cycle":
            opts["fail_on_cycle"] = True
        elif a in ("-h", "--help"):
            sys.stdout.write(__doc__)
            sys.exit(0)
        elif a.startswith("-"):
            die("unknown option %s" % a)
        else:
            opts["db"] = a
        i += 1
    if not opts["db"]:
        sys.stderr.write(__doc__)
        sys.exit(2)
    if os.path.isdir(opts["db"]):
        opts["db"] = os.path.join(opts["db"], "compile_commands.json")
    return opts


def load_db(path):
    try:
        with open(path, encoding="utf-8", errors="replace") as f:
            return json.load(f)
    except OSError as e:
        die("cannot read %s: %s" % (path, e))
    except ValueError as e:
        die("malformed JSON in %s: %s" % (path, e))


def collect_units(db):
    """Return (translation units, ordered include dirs) as absolute paths."""
    units = []
    inc_dirs = []
    seen = set()
    for entry in db:
        base = entry.get("directory", ".")
        f = entry.get("file")
        if not f:
            continue
        units.append(os.path.realpath(os.path.join(base, f)))
        args = entry.get("arguments") or shlex.split(entry.get("command", ""))
        j = 0
        while j < len(args):
            a = args[j]
            d = None
            if a == "-I" and j + 1 < len(args):
                j += 1
                d = args[j]
            elif a.startswith("-I"):
                d = a[2:]
            if d:
                d = os.path.realpath(os.path.join(base, d))
                if d not in seen:
                    seen.add(d)
                    inc_dirs.append(d)
            j += 1
    return units, inc_dirs


def file_index(root):
    """Set of all existing files under root (for fast include resolution)."""
    files = set()
    for cur, dirs, names in os.walk(root):
        dirs[:] = [d for d in dirs if not d.startswith(".")]
        for n in names:
            files.add(os.path.join(cur, n))
    return files


def build_file_graph(units, inc_dirs, root, existing):
    """BFS from translation units through project includes; return edges."""
    edges = set()   # (src_file, dst_file), both under root
    visited = set()
    resolve_cache = {}
    queue = [u for u in units if u.startswith(root + os.sep) or u == root]

    def resolve(kind, name, cur_dir):
        key = (kind, name, cur_dir if kind == '"' else None)
        if key in resolve_cache:
            return resolve_cache[key]
        result = None
        cands = []
        if kind == '"':
            cands.append(os.path.normpath(os.path.join(cur_dir, name)))
        for d in inc_dirs:
            cands.append(os.path.normpath(os.path.join(d, name)))
        for c in cands:
            if c in existing and c.startswith(root + os.sep):
                result = c
                break
        resolve_cache[key] = result
        return result

    while queue:
        f = queue.pop()
        if f in visited:
            continue
        visited.add(f)
        try:
            with open(f, encoding="utf-8", errors="replace") as fp:
                text = fp.read()
        except OSError:
            continue
        cur_dir = os.path.dirname(f)
        for kind, name in INCLUDE_RE.findall(text):
            dst = resolve(kind, name, cur_dir)
            if dst and dst != f:
                edges.add((f, dst))
                if dst not in visited:
                    queue.append(dst)
    return edges, len(visited)


def module_of(path, root, depth):
    rel = os.path.relpath(os.path.dirname(path), root)
    if rel == ".":
        return "."
    parts = rel.split(os.sep)
    return "/".join(parts[:depth])


def strongly_connected(adj):
    """Tarjan SCC; returns components with >= 2 nodes."""
    index = {}
    low = {}
    on_stack = set()
    stack = []
    sccs = []
    counter = [0]
    sys.setrecursionlimit(10000)

    def strong(v):
        index[v] = low[v] = counter[0]
        counter[0] += 1
        stack.append(v)
        on_stack.add(v)
        for w in adj.get(v, ()):
            if w not in index:
                strong(w)
                low[v] = min(low[v], low[w])
            elif w in on_stack:
                low[v] = min(low[v], index[w])
        if low[v] == index[v]:
            comp = []
            while True:
                w = stack.pop()
                on_stack.discard(w)
                comp.append(w)
                if w == v:
                    break
            if len(comp) >= 2:
                sccs.append(sorted(comp))

    for v in sorted(adj):
        if v not in index:
            strong(v)
    return sccs


def main(argv):
    opts = parse_args(argv)
    db = load_db(opts["db"])
    units, inc_dirs = collect_units(db)
    if not units:
        die("no translation units in %s" % opts["db"])
    root = opts["root"] or os.path.commonpath(units)
    existing = file_index(root)
    file_edges, files_seen = build_file_graph(units, inc_dirs, root, existing)

    adj = {}        # module -> set of modules it depends on
    pair_count = {}  # (src_mod, dst_mod) -> file-level edge count
    for src, dst in file_edges:
        ms = module_of(src, root, opts["depth"])
        md = module_of(dst, root, opts["depth"])
        if ms == md:
            continue
        adj.setdefault(ms, set()).add(md)
        adj.setdefault(md, set())
        pair_count[(ms, md)] = pair_count.get((ms, md), 0) + 1

    ca = {m: 0 for m in adj}
    for m, deps in adj.items():
        for d in deps:
            ca[d] += 1
    rows = []
    for m in adj:
        ce = len(adj[m])
        i_val = ce / (ca[m] + ce) if (ca[m] + ce) else 0.0
        rows.append((m, ca[m], ce, i_val))

    sccs = strongly_connected(adj)
    in_cycle = {m for comp in sccs for m in comp}

    if opts["csv"]:
        print("module,ca,ce,instability,in_cycle")
        for m, c_a, c_e, i_val in sorted(rows):
            print("%s,%d,%d,%.2f,%d" % (m, c_a, c_e, i_val,
                                        1 if m in in_cycle else 0))
    else:
        print("== Module cycles: %d ==" % len(sccs))
        for comp in sccs[:opts["top"]]:
            print("  " + " <-> ".join(comp))
        warn = sorted((r for r in rows
                       if r[1] >= opts["min_ca"] and r[3] >= 0.5),
                      key=lambda r: (-r[1] * r[3], r[0]))
        print("== Unstable but widely depended on"
              " (Ca >= %d, I >= 0.5): %d ==" % (opts["min_ca"], len(warn)))
        for m, c_a, c_e, i_val in warn[:opts["top"]]:
            print("  %-40s Ca=%-3d Ce=%-3d I=%.2f" % (m, c_a, c_e, i_val))
        print("== Module metrics (top fan-in) ==")
        for m, c_a, c_e, i_val in sorted(rows, key=lambda r: -r[1])[:opts["top"]]:
            mark = "  [cycle]" if m in in_cycle else ""
            print("  %-40s Ca=%-3d Ce=%-3d I=%.2f%s" % (m, c_a, c_e, i_val, mark))
        print("== Summary ==")
        print("  TUs: %d, files parsed: %d, modules: %d (depth %d),"
              " module deps: %d, cycles: %d"
              % (len(units), files_seen, len(adj), opts["depth"],
                 len(pair_count), len(sccs)))
    if opts["fail_on_cycle"] and sccs:
        sys.exit(1)


if __name__ == "__main__":
    main(sys.argv)
